services:
  db:
    image: postgres:16-alpine
    container_name: billiard-db
    networks:
      - billiard-networks
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=billiard_matchmaking
      - TZ=Asia/Jakarta
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    networks:
      - billiard-networks
    container_name: billiard-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Jakarta
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/billiard_matchmaking
      - JWT_SECRET=billiard-pointer:platform-matchmaking-online
      - STAFF_USERNAME=staff
      - STAFF_PASSWORD=staffsecret0123
      - PORT=3000
      - NODE_ENV=production
      - SHOW_QUERY_LOG=false
    restart: unless-stopped
    volumes:
      - ./avatars:/app/avatars:ro
    depends_on:
      - db

  player:
    networks:
      - billiard-networks
    container_name: billiard-player
    build:
      context: ./frontend/player
      dockerfile: Dockerfile
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./avatars:/usr/share/nginx/html/avatars:ro
      - ./frontend/player/script.js:/usr/share/nginx/html/script.js:ro
    environment:
      - TZ=Asia/Jakarta
    ports:
      - '1123:80'
    restart: unless-stopped
    depends_on:
      - backend

  staff:
    networks:
      - billiard-networks
    container_name: billiard-staff
    build:
      context: ./frontend/staff
      dockerfile: Dockerfile
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./avatars:/usr/share/nginx/html/avatars:ro
      - ./frontend/staff/script.js:/usr/share/nginx/html/script.js:ro
    environment:
      - TZ=Asia/Jakarta
    ports:
      - '1124:80'
    restart: unless-stopped
    depends_on:
      - backend

networks:
  billiard-networks:
    driver: bridge
