services:
  db:
    image: postgres:16-alpine
    container_name: billiard-db
    ports:
      - '1111:5432'
    networks:
      - billiard-networks
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=billiard_matchmaking
      - TZ=Asia/Jakarta
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    networks:
      - billiard-networks
    container_name: billiard-backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    build:
      context: ./backend
    environment:
      - TZ=Asia/Jakarta
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/billiard_matchmaking
      - JWT_SECRET=devel:platform-matchmaking-online
      - STAFF_USERNAME=staff
      - STAFF_PASSWORD=staffsecret0123
      - NODE_ENV=production
      - SHOW_QUERY_LOG=false
    restart: unless-stopped
    depends_on:
      - db

networks:
  billiard-networks:
    driver: bridge
